// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-formations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-formations.ts
var list_formations_default = defineTool({
  name: "list_formations",
  title: "Lister les sessions de formation",
  description: "Liste les sessions de formation (titre, type, dates, lieu, statut). Filtre optionnel par statut ou par sessions \xE0 venir uniquement.",
  inputSchema: {
    status: z.string().trim().optional().describe("Filtrer par statut, ex: planifiee, en_cours, terminee"),
    upcoming_only: z.boolean().optional().describe("Ne garder que les sessions dont la date de d\xE9but est future"),
    limit: z.number().int().optional().describe("Nombre maximum de sessions (d\xE9faut 25, max 100)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, upcoming_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("formations").select("id, title, type, status, start_date, end_date, location, max_participants").order("start_date", { ascending: true }).limit(max);
    if (status) query = query.eq("status", status);
    if (upcoming_only) query = query.gte("start_date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { formations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-stagiaires.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var search_stagiaires_default = defineTool2({
  name: "search_stagiaires",
  title: "Rechercher des stagiaires",
  description: "Recherche des stagiaires par nom ou pr\xE9nom et renvoie leurs coordonn\xE9es, statut, num\xE9ro de carte pro et dates d'expiration.",
  inputSchema: {
    query: z2.string().trim().optional().describe("Texte recherch\xE9 dans le nom ou le pr\xE9nom"),
    limit: z2.number().int().optional().describe("Nombre maximum de r\xE9sultats (d\xE9faut 25, max 100)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    const supabase = supabaseForUser(ctx);
    let req = supabase.from("stagiaires").select(
      "id, first_name, last_name, email, phone, city, status, carte_pro_number, carte_pro_expiry, mac_aps_expiry"
    ).order("last_name", { ascending: true }).limit(max);
    if (query) {
      const safe = query.replace(/[%,()]/g, " ");
      req = req.or(`first_name.ilike.%${safe}%,last_name.ilike.%${safe}%`);
    }
    const { data, error } = await req;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { stagiaires: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-formation-participants.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_formation_participants_default = defineTool3({
  name: "list_formation_participants",
  title: "Lister les participants d'une session",
  description: "Liste les stagiaires inscrits \xE0 une session de formation donn\xE9e, avec leur statut (inscrit, present, absent, valide, echec).",
  inputSchema: {
    formation_id: z3.string().trim().describe("Identifiant de la session de formation")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ formation_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("formation_participants").select("id, status, stagiaire_id, stagiaires(first_name, last_name, email)").eq("formation_id", formation_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { participants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-expiring-certifications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var MONTH_MS = 30 * 24 * 60 * 60 * 1e3;
var list_expiring_certifications_default = defineTool4({
  name: "list_expiring_certifications",
  title: "\xC9ch\xE9ances de cartes pro et MAC APS",
  description: "Liste les stagiaires dont la carte professionnelle ou le MAC APS expire dans les prochains mois (ou est d\xE9j\xE0 expir\xE9), pour planifier les recyclages.",
  inputSchema: {
    months_ahead: z4.number().int().optional().describe("Horizon en mois (d\xE9faut 6)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ months_ahead }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const horizonMonths = Math.min(Math.max(months_ahead ?? 6, 1), 24);
    const cutoff = new Date(Date.now() + horizonMonths * MONTH_MS).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("stagiaires").select("id, first_name, last_name, email, carte_pro_expiry, mac_aps_expiry").or(`carte_pro_expiry.lte.${cutoff},mac_aps_expiry.lte.${cutoff}`).limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const rows = (data ?? []).flatMap(
      (s) => [
        ["carte_pro", s.carte_pro_expiry],
        ["mac_aps", s.mac_aps_expiry]
      ].filter(([, date]) => date && date <= cutoff).map(([kind, date]) => ({
        stagiaire_id: s.id,
        nom: `${s.first_name ?? ""} ${s.last_name ?? ""}`.trim(),
        email: s.email,
        certification: kind,
        date_expiration: date,
        expire: date < today
      }))
    );
    rows.sort((a, b) => String(a.date_expiration).localeCompare(String(b.date_expiration)));
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { echeances: rows }
    };
  }
});

// src/lib/mcp/tools/create-incident.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var create_incident_default = defineTool5({
  name: "create_incident",
  title: "Cr\xE9er un incident (main courante)",
  description: "Enregistre un nouvel incident dans la main courante au nom de l'utilisateur connect\xE9.",
  inputSchema: {
    title: z5.string().trim().describe("Titre court de l'incident"),
    description: z5.string().trim().optional().describe("Description d\xE9taill\xE9e"),
    location: z5.string().trim().optional().describe("Lieu de l'incident"),
    severity: z5.string().trim().optional().describe("S\xE9v\xE9rit\xE9, ex: faible, moyenne, elevee, critique"),
    occurred_at: z5.string().trim().optional().describe("Date/heure ISO de survenue (d\xE9faut: maintenant)")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, location, severity, occurred_at }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const payload = {
      author_id: ctx.getUserId(),
      title,
      description: description ?? null,
      location: location ?? null,
      occurred_at: occurred_at ?? (/* @__PURE__ */ new Date()).toISOString()
    };
    if (severity) payload.severity = severity;
    const { data, error } = await supabase.from("incidents").insert(payload).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { incident: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hvqbggkfqssvbmracscm";
var mcp_default = defineMcp({
  name: "security-guard-pro",
  title: "Security Guard Pro",
  version: "0.1.0",
  instructions: "Outils du CRM de s\xE9curit\xE9 priv\xE9e et de formation (SecureCRM). Utilisez list_formations pour les sessions, search_stagiaires pour retrouver un stagiaire, list_formation_participants pour les inscrits d'une session, list_expiring_certifications pour les \xE9ch\xE9ances de cartes pro / MAC APS, et create_incident pour enregistrer un incident dans la main courante. Toutes les donn\xE9es sont filtr\xE9es selon les droits de l'utilisateur connect\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_formations_default,
    search_stagiaires_default,
    list_formation_participants_default,
    list_expiring_certifications_default,
    create_incident_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
